# Generated by Django 2.0.2 on 2018-02-20 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'Creada'), (1, 'Activada'), (2, 'Bloqueada')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to='backend.Account'),
        ),
    ]
